sudo: required
services: 
    - docker

before_install:
    - docker build -t nagameena/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true nagameena/react-test npm test -- --coverage

after_success:
    - docker build -t nagameena/multi-client ./client
    - docker build -t nagameena/multi-nginx ./nginx
    - docker build -t nagameena/multi-server ./server
    - docker build -t nagameena/multi-worker ./worker
# Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Take those images and push them to docker hub
    - docker push nagameena/multi-client
    - docker push nagameena/multi-nginx
    - docker push nagameena/multi-server
    - docker push nagameena/multi-worker

deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-ap-south-1-676609059609"
    bucket_path: "docker-multi"
    on:
        branch: master
    edge: true
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: "$AWS_SECRET_KEY"